apiVersion: v1
kind: Service
metadata:
  name: docker-spring-boot-containers
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 12345
  selector:
    app: docker-spring-boot-containers

